export const stepsNames = {
  "attraction-challenge": "",
  "5-blue-car-challenge": "",
  "change-wheel-challenge": "",
  "fuel-stop-challenge": "",
  "nose-challenge": "",
  "potatoe-challenge": "",
  "push-car-challenge": "",
  "state-product-challenge": "",
  "5-toyota-challenge": "",
  "departement-blason-hint": "",
  "celebrity-hint": "",
  "city-population-hint": "",
  "compass-direction-hint": "",
  "departement-hint": "",
  "dish-hint": "",
  "departement-flag-hint": "",
  "haut-gauche-bas-droite-hint": "",
  "near-city-hint": "",
  "precise-description-hint": "",
  "rebus-hint": "",
  "shoes-hint": "",
  "state-hint": "",
  "tourism-hint": "",
  "weather-hint": "",
  "proximity-notification": "Notification de Proximité",
};
