export const stepsNames = {
  "attraction-challenge": "",
  "5-blue-car-challenge": "",
  "change-wheel-challenge": "",
  "fuel-stop-challenge": "",
  "nose-challenge": "",
  "potatoe-challenge": "",
  "push-car-challenge": "",
  "state-product-challenge": "",
  "5-toyota-challenge": "",
  "departement-blason-hint": "Le Pavillon du Bâtiment",
  "celebrity-hint": "",
  "city-population-hint": "COMBIEN ?!",
  "compass-direction-hint": "La carte de Dora",
  "departement-hint": "",
  "dish-hint": "Intervention de Ratatouille",
  "departement-flag-hint": "",
  "haut-gauche-bas-droite-hint": "",
  "near-city-hint": "",
  "precise-description-hint": "",
  "rebus-hint": "",
  "shoes-hint": "Conseil d'un Hobbit",
  "state-hint": "",
  "tourism-hint": "Astu'Insta",
  "weather-hint": "La météo de Gulli",
  "proximity-notification": "Notification de Proximité",
};
